### ISSUE TITLE
My branch has some new things

### ISSUE THREAD

**Issue by huffstler** [huffstler/cisc475-DanceDB#1]
I'd like to get everyone on the same page before I merge stuff. 

If you go on the homepage of the project and looks at the "Branches" section right next to the "Commits" section, you'll notice it says 2. I've made a separate branch so as not to make any merge conflicts with other peoples code. It includes an entire eclipse project file and I'm not sure if you guys want me to push the whole file or just the files that I've worked on thus far. If you want to see what I mean, click [this](https://github.com/huffstler/cisc475-DanceDB/tree/pat) to see my branch, with the included code.

Let me know in Whatsapp or on here what you'd be more comfortable with me doing. 👍

**Comment by wanxinli** [comment]
Cool. I have my branch too. I suggest just to pull the class file in the master branch, which you are working on, but  not the entire project.
